Translate help document to English
epam/miew pull request #434
Opened 2023-07-11 00:19 UTC by NataliaDSmirnova

## Description

- The project is an open source project, so all documents should be provided in English

2023-07-12 16:14 UTC, paulsmirnov requested changes
Thanks a lot! Please check my suggestions in the comments

2023-07-12 16:14 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +lines.
```suggestion
then executed in the virtual machine, whether in the browser or from the command line.
```

2023-07-12 16:14 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +[new features are added][], passing complex and lengthy [selection and approval system][].
```suggestion
At the same time, it constantly is developing. Every year 
[new features are added][] to the language, passing complex and lengthy [selection and approval process][].
```

2023-07-12 16:14 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +[selection and approval system]: https://tc39.github.io/process-document/
```suggestion
[selection and approval process]: https://tc39.github.io/process-document/
```

2023-07-12 16:18 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +development.
```suggestion
means. A more convenient solution is to use a suitable development environment.
```

2023-07-12 16:19 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +jetbrains. This is a commercial program that requires a personal or corporate
```suggestion
JetBrains. This is a commercial program that requires a personal or corporate
```

2023-07-12 16:23 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
> +-   source code: <https://github.com/epam/miew/>
```suggestion
-   source code: <https://github.com/epam/miew/>

Disclaimer: this text was written in 2018 for students that likely didn't know much about Git, JavaScript, et al.
In 2023 we translated it in English as-is, so some passages may sound archaic or outdated now. Still, it contains
a pretty good background overview and introduction to Miew development.
```

2023-07-12 16:43 UTC, NataliaDSmirnova commented on tools/templates/getting-started-for-dummies.md
> +Living organisms consists of [proteins][], which are macromolecules
Thank you, but I'd leave it as is.

2023-07-12 16:51 UTC, NataliaDSmirnova commented on tools/templates/getting-started-for-dummies.md
> +However, the [secondary structure][], which features [spirals][], [layers][],
sure

2023-07-14 15:27 UTC, paulsmirnov commented on tools/templates/getting-started-for-dummies.md
>  is still prototype.
```suggestion
is still prototype-based.
```

2023-07-14 15:28 UTC, paulsmirnov approved these changes
Thanks! I think we need to squash all individual commits.

2023-07-14 15:54 UTC, merged