447 bump node to version 18 2
epam/miew pull request #451
Opened 2023-08-13 12:20 UTC by DmitryLukyanov

_(Please do not forget to update the PR title using imperative mood as with commit messages; and delete this line, of course)_

## Description
Migration to node 18

## Type of changes
Configuration changes.

## Checklist
_(Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code)_

- [X] I have read [CONTRIBUTING](https://github.com/epam/miew/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/epam/miew/blob/master/CODE_OF_CONDUCT.md) guides.
- [X] I have followed the code style of this project.
- [X] I have run `yarn run ci`: lint and tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation / The changes do not need docs update.

2023-08-13 15:50 UTC, paulsmirnov requested changes
The changes seem reasonable. Thank you!

I've noticed one issue with the `packages/app`: images are missing in the Mode/Color dropdowns and in the main menu. The same works fine in the `main` branch. Perhaps, is it something to do with the new webpack. Could you please confirm that it is not an issue with only my setup (I've checked twice)?

Steps to reproduce:
```bash
nvm use 18  # or "nvm use 14" for the main branch
yarn install
cd packages/lib
yarn run ci
cd ../app
yarn start
```

Actual vs expected:
![shot-20230813-112843](https://github.com/epam/miew/assets/11373544/c9737e38-9a83-400d-8cb1-fbfa0e9b1ce6) ![shot-20230813-114334](https://github.com/epam/miew/assets/11373544/997a6bda-5ecc-496d-9b68-44b182a3d088)

2023-08-13 16:15 UTC, DmitryLukyanov commented
> The changes seem reasonable. Thank you!
> 
> I've noticed one issue with the `packages/app`: images are missing in the Mode/Color dropdowns and in the main menu. The same works fine in the `main` branch. Perhaps, is it something to do with the new webpack. Could you please confirm that it is not an issue with only my setup (I've checked twice)?
> 
> Steps to reproduce:
> 
> ```shell
> nvm use 18  # or "nvm use 14" for the main branch
> yarn install
> cd packages/lib
> yarn run ci
> cd ../app
> yarn start
> ```
> 
> Actual vs expected: ![shot-20230813-112843](https://user-images.githubusercontent.com/11373544/260313419-c9737e38-9a83-400d-8cb1-fbfa0e9b1ce6.png) ![shot-20230813-114334](https://user-images.githubusercontent.com/11373544/260313424-997a6bda-5ecc-496d-9b68-44b182a3d088.png)

yeah, I see the same, required links on images gives 404. I will look at it.

Btw, do we have any test on this?

2023-08-13 16:20 UTC, paulsmirnov commented
> Btw, do we have any test on this?

None that I'm aware of. We'll need to decide on the implementation because it doesn't look obvious. HTML snapshots are not enough while 3D screenshots can be different depending on software and hardware.

2023-08-13 16:30 UTC, DmitryLukyanov commented
> > Btw, do we have any test on this?
> 
> None that I'm aware of. We'll need to decide on the implementation because it doesn't look obvious. HTML snapshots are not enough while 3D screenshots can be different depending on software and hardware.

we can check that at least one picture link doesn't return 404 :)

2023-08-14 04:24 UTC, NataliaDSmirnova submitted a review, later dismissed
Awesome job!

2023-08-14 15:46 UTC, NataliaDSmirnova commented
@DmitryLukyanov, 
It seems the problem with images and `url-loader` limit question may be linked. The reason `url-loader` is deprecated in Webpack5.
See https://v4.webpack.js.org/loaders/url-loader/ and https://webpack.js.org/guides/asset-modules/ 

The information above is provided by @paulsmirnov and @AlinaFirsova. I hope it helps 🙂

2023-08-27 15:22 UTC, DmitryLukyanov commented on .appveyor.yml
> +    - nodejs_version: "18"
It looks like it's related to lerna that we're going to remove in a parallel ticket

2023-08-28 03:17 UTC, NataliaDSmirnova approved these changes
Great! I've checked:
- lib: yarn build,  yarn start -> demo works (shortcuts also), examples work
- app: yarn build, yarn start -> app works (shortcuts also)

Big thanks ♥

2023-08-28 15:23 UTC, paulsmirnov approved these changes
Awesome! The steps that failed previously work for me now. I see the images. I hope we also understand the cause :)

2023-08-28 15:25 UTC, paulsmirnov commented
Are we going to get rid of the deprecated modules later in a separate task?

2023-08-28 19:26 UTC, merged